version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amber-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cdrz77lefvfu"
s3_prefix = "amber-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"amberHits\""
